# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0IZSw46jZrWcl5jd6ksfEvxCupVlkFA
"""

from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure()
ax = plt.axes(projection ='3d')
z =  np.linspace(0, 1, 100)
x = z*np.sin(20*z)
y = z*np.cos(20*z)
ax.plot3D(x,y,z,'gray')
ax.set_title('3D line plot')
fig.savefig('3dline.png', bbox_inches='tight')
plt.show()

from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure()
ax = plt.axes(projection ='3d')
z =  np.linspace(0, 1, 100)
x = z*np.sin(20*z)
y = z*np.cos(20*z)
c = x + y
ax.scatter(x,y,z,c=c)
ax.set_title('3D Scatter plot')
fig.savefig('3dscatter.png', bbox_inches='tight')
plt.show()