# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ak3aEos95fZ1jZtEp8NLcy8eHThbmWQ3
"""

import numpy as np
import matplotlib.pyplot as plt
xlist = np.linspace(-3.0, 3.0, 100)
ylist = np.linspace(-3.0, 3.0, 100)
X, Y = np.meshgrid(xlist,ylist)
Z = np.sqrt(X**2 + Y**2)
fig,ax=plt.subplots(1,1)
cp = ax.contourf(X,Y,Z)
fig.colorbar(cp)
ax.set_title('Filled Countours Plot')
ax.set_xlabel('x(cm)')
ax.set_ylabel('y(cm)')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x,y = np.meshgrid(np.arange(-2,2,.2),np.arange(-2,2,.25))
z = x*np.exp(-x**2-y**2)
v, u = np.gradient(z,.2,.2)
fig,ax = plt.subplots()
q = ax.quiver(x,y,u,v)
plt.show()