# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdPaMrYxUiDJZdzgjmAz2KuPFy7L94OV
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.plot([1,2,3,4,5,6,7,8,9,10], [2,4.5,1,2,3.5,2,1,2,3,2])
plt.title("Results")
plt.xlabel("Semester")
plt.ylabel("Grade")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
plt.plot([1,2,3,4,5,6,7,8,9,10], [2,4.5,1,2,3.5,2,1,2,3,2])
plt.title("Results")
plt.xlabel("Semester")
plt.ylabel("Grade")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
print(style.available)