# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lv5oaKhfZCwCwlsGjl8ITsZOG-mA1P94
"""

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("iris")
sns.lmplot('petal_width','petal_length', data=iris, hue='species',palette='Set1', fit_reg=False,
scatter_kws={"s": 70})
ax=plt.gca()
ax.set_title("Plotting using the Iris dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
sns.set_style("whitegrid")
data =pd.read_csv('/content/salary.csv')
sns.swarmplot(x="gender",y="salary",data=data)
ax=plt.gca()
ax.set_title("Salary distribuition")
plt.show()