# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8ius0moxRECLKpY0kMKnrHkF8Rb6OCC
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
data = np.random.rand(5, 6)
plt.pcolor(data)
plt.show()

data = np.random.rand(5, 6)
plt.pcolor(data, cmap='YlGnBu_r')
plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5, 5, N),
np.linspace(-4, 4, N))
Z = (X**2 + Y**2)
# You can visualize it as follows:
plt.pcolor(X, Y, Z,cmap='YlGnBu_r')
plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5, 5, N),
np.linspace(-5, 5, N))
Z = (X**2 + Y**2)
img = plt.imshow(Z, cmap='YlGnBu_r')
plt.colorbar(img)
plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5, 5, N),
np.linspace(-5, 5, N))
Z = (X**2 + Y**2)
img = plt.imshow(Z, cmap='coolwarm')
plt.colorbar(img, shrink=0.6)
plt.show()

N = 100
X, Y = np.meshgrid(np.linspace(-5, 5, N),
np.linspace(-5, 5, N))
Z = (X**2 + Y**2)
img = plt.imshow(Z, cmap='coolwarm')
plt.colorbar(img, extend='both')
plt.show()