# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1F5DjdRkPxa4gzPs01nxBzeC_2W7zic
"""

import numpy as np
import pandas as pd

days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
Mumbai=[np.nan,27,29,30,25,26,29]
Delhi=[33,35,34,np.nan,32,34,36]
dic={"Days":days,"Mumbai":Mumbai,"Delhi":Delhi}
df=pd.DataFrame(dic)
df

df.info()

df.dropna(how="all")

df

mmean = df["Mumbai"].mean()
dmean = df["Delhi"].mean()
df["Mumbai"].fillna(mmean,inplace=True)
df["Delhi"].fillna(dmean,inplace=True)
df

