# -*- coding: utf-8 -*-
"""Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy0R7CBL91n4GCrxjkQv2FbdPpnwluQ3
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/cars.csv')

df.head()

df.info()

df["normalized-losses"].value_counts()

df["horsepower"].value_counts()

df.isna().sum()

#Step 1: Replace the missing values with nan
df["normalized-losses"].replace("?",np.nan,inplace=True)
df["horsepower"].replace("?",np.nan,inplace=True)

#Step 2: Change the datatype
df["normalized-losses"]=df["normalized-losses"].astype("float")
df["horsepower"]=df["horsepower"].astype("float")

#Step 3: get the mean
nlmean=df["normalized-losses"].mean()
hpmean=df["horsepower"].mean()

#Step 4: use the fillna method
df["normalized-losses"].fillna(nlmean,inplace=True)
df["horsepower"].fillna(hpmean,inplace=True)
print(df)