# -*- coding: utf-8 -*-
"""Untitled104.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6t83sgDWMZK3amfmD5St29x92dYuS0j
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
tips = sns.load_dataset("tips")
sns.displot(x='total_bill',y='tip', data=tips)
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip',hue='size', data=tips)
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip', data=tips, rug=True,
kind='hist', bins=30)
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip', data=tips, kind='kde')
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip',data=tips, rug=True,kind='kde')
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip',data=tips, rug=True,kind='kde', col='size')
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', y='tip',data=tips, rug=True,kind='kde', row='size')
plt.show()