# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Udt7H01ykjf_r6V8zguGR5asyMkN02H_
"""

import numpy as np
import matplotlib.pyplot as plt
N = 16
x = np.linspace(0, 15, N)
y = np.logspace(0.1, 2, N)
print(y)
plt.plot(x, y, 'o--')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
N = 16
x = np.linspace(0, 15, N)
y = np.geomspace(0.1, 2000, N)
print(y)
plt.plot(x, y, 'o--')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(6)
print(x)
type(x)
y=x+1
plt.plot(x, y, 'o--')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
x = [4, 5, 3, 1, 6, 7]
plt.plot(x)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(25)
plt.plot(x)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(25)
plt.plot(x, [(y**3 + 1) for y in x])
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(25)
plt.plot(x, x**3 + 1)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(7)
plt.plot(x, -x**2)
plt.plot(x, -x**3)
plt.plot(x, -2*x)
plt.plot(x, -2**x)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(7)
plt.plot(x, -x**2, x, -x**3,x, -2*x, x, -2**x)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
x = np.array([[3, 2, 5, 6], [7, 4, 1, 5]])
plt.plot(x)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
data = np.random.randn(2, 10)
print(data)
plt.plot([data[0], data[1]])
plt.show()