# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3yBrfWCHi6QjbrWHTbPEfFVm2V2Z6u1
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
plt.bar([1,2,3,4,5,6,7,8,9,10],[2,4.5,1,2,3.5,2,1,2,3,2], label ="Jim",color="m",
align="center",alpha=0.5)
plt.bar([1,2,3,4,5,6,7,8,9,10],[1.2,4.1,0.3,4,5.5,4.7,4.8,5.2,1,1.1],label="Tim", 
color="g",align="center",alpha=0.5)
plt.title("Results")
plt.xlabel("Semester")
plt.ylabel("Grade")
plt.legend()
plt.grid(True,color="y")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
rainfall=[17,9,16,3,21,7,8,4,6,21,4,1]
months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
plt.bar(months, rainfall, align='center', color='orange')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
rainfall=[17,9,16,3,21,7,8,4,6,21,4,1]
months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
plt.bar(range(len(rainfall)),rainfall,align='center',color='orange')
plt.xticks(range(len(rainfall)),months,rotation='vertical')
plt.show()