# -*- coding: utf-8 -*-
"""Untitled95.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rw_gcaY4ezKPeYaSO_1jRSZuqEElVuvx
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(4)
y = np.random.rand(4)
plt.bar(x,y)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
y = np.random.rand(3,4)
plt.bar(x + 0.00, y[0], color = 'b', width = 0.25)
plt.bar(x + 0.25, y[1], color = 'g', width = 0.25)
plt.bar(x + 0.50, y[2], color = 'r', width = 0.25)
plt.show()

x = np.arange(4)
y = np.random.rand(4)
plt.barh(x, y)
plt.show()

y = np.random.rand(3,4)
plt.barh(x + 0.00, y[0],color='b', height=0.25)
plt.barh(x + 0.25, y[1],color='g', height=0.25)
plt.barh(x + 0.50, y[2],color='r', height=0.25)
plt.show()

N = 1000
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
size = (20)
plt.scatter(x, y, s=size, c=colors, alpha=1)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
N = 1000
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
size = (50 * x * y)
plt.scatter(x, y, s=size, c=colors, alpha=1)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
x = [1, 3, 5, 1, 2, 4, 4, 2, 5, 4, 3, 1, 2]
n_bins=5
plt.hist(x, bins=n_bins)
plt.show()

np.random.seed(31415)
n_points = 10000
n_bins = 15
x = np.random.randn(n_points)
plt.hist(x, bins=n_bins)
plt.show()

np.random.seed(31415)
n_points = 10000
x = np.random.randn(n_points)
y = np.random.randn(n_points)
plt.hist2d(x, y, bins=50)
plt.show()

np.random.seed(31415)
n_points = 10000
x = np.random.randn(n_points)
plt.hist(x, 20, density=True,
histtype='stepfilled',
facecolor='g', alpha=0.5)
plt.show()

np.random.seed(31415)
n_points = 10000
x = np.random.randn(n_points)
plt.hist(x, 20, density=True,
histtype='step')
plt.show()