# -*- coding: utf-8 -*-
"""Untitled103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VoyJlnGbzEDMufhfKNabt2-0CsZZijHK
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.DataFrame(np.random.randn(100, 4),
index=pd.date_range("9/3/2022",
periods=100),
columns=list("ABCD"))
df = df.cumsum()
sns.relplot(x=df.index, y='A', kind="line", data=df)
plt.xticks(rotation=45)
plt.show()

df = pd.DataFrame(np.random.randn(100, 4),
index=pd.date_range("9/3/2022",
periods=100),
columns=list("ABCD"))
df = df.cumsum()
sns.lineplot(x=df.index,
y='A', data=df)
plt.xticks(rotation=45)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
x = np.random.randn(100)
sns.displot(x)
plt.show()

x = np.random.randn(100)
sns.displot(x, kind='hist')
plt.show()

x = np.random.randn(100)
sns.displot(x, kind='kde')
plt.show()

x = np.random.randn(100)
sns.displot(x, kind='ecdf')
plt.show()

x = np.random.randn(100)
sns.displot(x, kind='hist', kde=True)
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', data=tips, kind='hist')
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', data=tips,
kind='hist', bins=30, kde=True)
plt.show()

tips = sns.load_dataset("tips")
sns.displot(x='total_bill', data=tips,
kind='kde', hue='size')
plt.show()