# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YwNLaQlOlxe7GDdrEHw4_BRvuYXv1r4W
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
series = pd.Series(3 * np.random.rand(4),
index=['A', 'B', 'C', 'D'],
name='series')
print(series)
plt.figure()
series.plot.pie(figsize=(6, 6))
plt.show()

df = pd.DataFrame(3 * np.random.rand(4, 2),
index=['A', 'B', 'C', 'D'],
columns=['X', 'Y'])
print(df)
plt.figure()
df.plot.pie(figsize=(6, 6), subplots=True)
plt.show()

series = pd.Series(3 * np.random.rand(4),
index=['A', 'B', 'C', 'D'],
name='series')
print(series)
plt.figure()
series.plot.pie(labels=['A', 'B', 'C', 'D'],
                colors=['r', 'g', 'b', 'c'],
                autopct='%.2f', fontsize=20,
figsize=(6,6))
plt.show()

series = pd.Series([0.1] * 4,
index=['A', 'B', 'C', 'D'],
name='series2')
print(series)
plt.figure()
series.plot.pie(figsize=(6, 6))
plt.show()

import seaborn as sns
sns.get_dataset_names()

iris = sns.load_dataset('iris')

iris

import seaborn as sns
sns.relplot(x='sepal_length',
y='sepal_width',
data=iris)
plt.grid('on')
plt.show()

sns.relplot(x='sepal_length',
y='sepal_width',
data=iris,
kind='scatter')
plt.grid('on')
plt.show()

sns.scatterplot(x='sepal_length',
y='sepal_width',
data=iris)
plt.grid('on')
plt.show()

sns.relplot(x='petal_length',
y='petal_width',
data=iris)
plt.grid('on')
plt.show()

sns.scatterplot(x='petal_length',
y='petal_width',
data=iris)
plt.grid('on')
plt.show()

sns.relplot(x='sepal_length',
y='sepal_width',
hue='species',
data=iris)
plt.grid('on')
plt.show()

sns.scatterplot(x='sepal_length',
y='sepal_width',
hue='species',
data=iris)
plt.grid('on')
plt.show()

sns.relplot(x='sepal_length', y='sepal_width',
hue='petal_length', style='species',
data=iris)
plt.grid('on')
plt.show()

sns.scatterplot(x='sepal_length', y='sepal_width',
hue='petal_length', style='species',
data=iris)
plt.grid('on')
plt.show()

sns.relplot(x='sepal_length', y='sepal_width',
size='petal_length', style='species',
hue='species', data=iris)
plt.grid('on')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.scatterplot(x='sepal_length', y='sepal_width',
size='petal_length', style='species',
hue='species', data=iris)
plt.grid('on')
plt.show()