# -*- coding: utf-8 -*-
"""Untitled94.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PiaZx-f4UXiVm9stOVwmET6w46qvD_C
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(10)
fig, ax = plt.subplots()
ax.plot(x, -x**2, label='-x**2')
ax.plot(x, -x**3, label='-x**3')
ax.plot(x, -2*x, label='-2*x')
ax.plot(x, -2**x, label='-2**x')
ax.set_xlabel('x = np.arange(10)')
ax.set_ylabel('y = f(x)')
ax.set_title('Simple Plot Demo')
ax.legend()
ax.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(10)
fig, ax = plt.subplots()
ax.plot(x, -x**2, label='-x**2')
ax.plot(x, -x**3, label='-x**3')
ax.plot(x, -2*x, label='-2*x')
ax.plot(x, -2**x, label='-2**x')
ax.set_xlabel('x = np.arange(10)')
ax.set_ylabel('y = f(x)')
ax.set_title('Simple Plot Demo')
ax.legend()
ax.grid(True)
ax.text(0.25, -5, "Simple Plot Demo")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(3)
plt.subplots_adjust(wspace=0.3,hspace=0.3)
plt.subplot(2, 2, 1)
plt.plot(x, -x**2)
plt.subplot(2, 2, 2)
plt.plot(x, -x**3)
plt.subplot(2, 2, 3)
plt.plot(x, -2*x)
plt.subplot(2, 2, 4)
plt.plot(x, -2**x)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(3)
fig, axs = plt.subplots(2, 2)
plt.subplots_adjust(wspace=0.3,hspace=0.3)
axs[0, 0].plot(x, -x**2)
axs[0, 1].plot(x, -x**3)
axs[1, 0].plot(x, -2*x)
axs[1, 1].plot(x, -2**x)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('ggplot')
data = np.random.randn(10)
plt.plot(data)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.show()

print(plt.style.available)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib  inline
import matplotlib.pyplot as plt
import numpy as np
data = np.random.randn(10)
plt.style.use('classic')
plt.plot(data)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.show()

plt.style.use('default')
plt.plot(data)
plt.show()

import matplotlib.pyplot as plt
n = 3
data = np.linspace(0, 2*n*np.pi, 300)
def sinusoidal(sty):
    plt.style.use(sty)
    fig, ax = plt.subplots()
    ax.plot(data, np.sin(data), label='Sine')
    ax.plot(data, np.cos(data), label='Cosine')
    ax.legend()

sinusoidal('default')
plt.show()

sinusoidal('ggplot')
plt.show()

sinusoidal('seaborn')
plt.show()

with plt.style.context('Solarize_Light2'):
    data = np.linspace(0, 6 * np.pi)
    plt.plot(np.sin(data), 'g.--')
    plt.show()