# -*- coding: utf-8 -*-
"""Untitled83.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YobV353FeesdhM0qsm9HsaE0z-78BrcV
"""

import nltk
nltk.download('punkt')
import nltk
nltk.download('stopwords')
from pathlib import Path
from textblob import TextBlob
blob = TextBlob(Path('/content/romeoandjuliet.txt').read_text())

from nltk.corpus import stopwords
stop_words = stopwords.words('english')

items = blob.word_counts.items()

items = [item for item in items if item[0] not in stop_words]

from operator import itemgetter
sorted_items = sorted(items, key=itemgetter(1), reverse=True)

top20 = sorted_items[1:21]

import pandas as pd
df = pd.DataFrame(top20, columns=['word', 'count'])
df

axes = df.plot.bar(x='word', y='count', legend=False)

import matplotlib.pyplot as plt
plt.gcf().tight_layout()