# -*- coding: utf-8 -*-
"""Untitled80.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S4YWgirj2mqNrG6XguWwhDZ1uz3ByDsO
"""

import nltk
nltk.download('brown')
import nltk
nltk.download('punkt')
import nltk
nltk.download('wordnet')
import textblob
from textblob import TextBlob
text = 'Today is a beautiful day. Tomorrow looks like bad weather.'
blob = TextBlob(text)
blob

from textblob import Word
word = Word('varieties')
word.stem()

word.lemmatize()

import pathlib
from pathlib import Path
from textblob import TextBlob
blob = TextBlob(Path('romeoandjuliet.txt').read_text())

blob.word_counts['juliet']

blob.word_counts['romeo']

blob.word_counts['thou']

blob.words.count('joy')

blob.noun_phrases.count('lady capulet')

from textblob import TextBlob
happy = Word('happy')
happy.definitions

happy.synsets

synonyms = set()

synonyms

lemmas = happy.synsets[0].lemmas()
lemmas

lemmas[0].antonyms()