# -*- coding: utf-8 -*-
"""Untitled76.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGmo6J-J2AvT8qjD8kIFz-68Y6Bsidmv
"""

import textblob
from textblob import TextBlob
text = 'Today is a beautiful day. Tomorrow looks like bad weather.'
blob = TextBlob(text)
blob

blob.sentiment

# Commented out IPython magic to ensure Python compatibility.
# %precision 3

blob.sentiment.polarity

blob.sentiment.subjectivity

import nltk
nltk.download('punkt')

for sentence in blob.sentences:
    print(sentence.sentiment)

import nltk
nltk.download('movie_reviews')

from textblob.sentiments import NaiveBayesAnalyzer

blob = TextBlob(text, analyzer=NaiveBayesAnalyzer())

blob

blob.sentiment

for sentence in blob.sentences:
    print(sentence.sentiment)