# -*- coding: utf-8 -*-
"""Untitled82.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-oRzNvi2obbbIAXEzioBIcRnGiq-kKb
"""

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stops = stopwords.words('english')

from textblob import TextBlob
blob = TextBlob('Today is a beautiful day.')

import nltk
nltk.download('punkt')
[word for word in blob.words if word not in stops]

from textblob import TextBlob
text = 'Today is a beautiful day. Tomorrow looks like bad weather.'
blob = TextBlob(text)
blob.ngrams()

blob.ngrams(5)