# -*- coding: utf-8 -*-
"""Cópia de Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-x7DvlGjF1B0Y-H7LOQuowa90D4BBMHi
"""

#import the numpy library
import numpy as np

#creating a one-dimensional numpy array
my_arr = np.array([1,2,3,4,5])
print(my_arr)

print(type(my_arr))

#using 'shape' command it is possible to see the number of rows and columns in the table
#as it is one dimensional it will only show the number of columns
print(my_arr.shape)

#creating a list of lists to create a 2D matrix and show the shape
my_array = np.array([[1,2,3,4,5], [5,4,3,2,1]])
print(my_array)
print(my_array.shape)

#creating a 3 dimensional list and print the number of rows, columns and depth
arr = np.array([[[1,2,3,4,5],[5,4,3,2,1]],[[6,7,8,9,10],[10,9,8,7,6]]])
print(arr)
print(arr.shape)

#creating a one-dimensional sequential array with the 'arange'
#using 'reshape' to turn it into a list with 3 rows and 2 columns
arr2 = np.arange(6)
print(arr2)
print(arr2.reshape(3,2))

#creating a one-dimensional array with zeros and one
array_zeros = np.zeros(5)
print(array_zeros)

array_ones = np.ones(5)
print(array_ones)