# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZDzyM32IsV9Ft1DijDoYyyG_K7Xejsj

importing library
"""

import numpy as np

"""Creating NumPy array"""

arr = np.array([1,2,3,4,5,6,7,8,9,10])

"""using where function"""

print(arr[np.where(arr%2==0)])

"""Replacing elements with where"""

arr2 = np.where(arr%2==0,0,arr)
print(arr2)

"""Replacing elements - put command"""

np.put(arr2,1,10)
print(arr2)

"""NaN values"""

arr = np.array([1,2,4,5,np.nan,0,2,3,np.nan,np.nan,0,3,4,6])
print(np.isnan(arr))

np.where(np.isnan(arr))

arr = np.where(np.isnan(arr),10,arr)
print(arr)

"""Reshape"""

arr = np.array([1,2,3,4,5,6])
arr2 = arr.reshape(2,3)
print(arr2)

arr3 = arr.reshape(3,2)
print(arr3)

"""stack command"""

np.hstack(arr2)

"""common values"""

a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1,12,3,45,23,67,4])
common = np.intersect1d(a,b)
print(common)

"""
Removing common values"""

np.setdiff1d(a,b)

"""Checking if elements are in the array"""

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.isin(a,[1,5,8]))

"""reversing arrangement"""

print(np.flip(a))

"""sorting elements"""

arr = np.array([10,45,32,67,2,0,20,45,78])
arr = np.sort(arr)
print(arr)

arr2 = np.array([[2,6,1],[8,2,0],[0,3,1]])
print(arr2)

arr2_0 = np.sort(arr2)
print(arr2_0)

"""sorting on the line"""

arr2_1 = np.sort(arr2,axis=1)
print(arr2_1)

"""sorting in column"""

arr2_2 = np.sort(arr2,axis=0)
print(arr2_2)

"""repeat sequence"""

arr = np.array([1,2,3])
arr2 = np.tile(arr,2)
print(arr2)

"""unique values"""

arr = np.array([1,2,3,4,1,4,0,2,3,1,0,5,10])
print(np.unique(arr))

"""Unique values ​​with count"""

values, score = np.unique(arr,return_counts=True)

print(values)

print(score)