# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_X4HhyfOoescfnd76k5c7Cfiz7MQW58l
"""

#importing numpy library
import numpy as np

#writing the matrix A
A = np.array([[2,5,13],[22,9,14],[4,15,19]])
print('\nA =',A)

#writing the matrix B
B = np.array([[0,1,1],[2,3,-1],[1,0,1]])
print('\nB =',B)

#multiplying the two matrices with command 'dot()'
print('\nA*B =',A.dot(B))

#joining the two matrices
np.concatenate([A,B])

#stacking the array vertically
np.vstack([A,B])

#horizontally stacking arrays
np.hstack([A,B])

#stacking the array along the third axis
np.dstack([A,B])

#creating an array with random numbers using the 'radint()' command
C = np.random.randint(1,20,9)
print(C)

#setting the seed so that the same random number is always generated
np.random.seed(32)

print(C)

#comparisons
a1 = np.array([1,2,2,1])
a2 = np.array([3,2,3,1])

a1 == a2

#checking if the matrices are the same
np.array_equal(a1,a2)

#calculating the variance of the matrix
np.var(a1)