# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PBFJK3wGjwh2SxaoggPqS6jeuHpVcxZr
"""

#creating an array
import numpy as np

a = np.array([45, 23, 32]) 
a

#adding a value without changing the original array using 'append'
print('\nAppend Array =',np.append(a,10))
print('\nOriginal Array =',a)

print('\nAppend Array =',np.append(a,-3))
print('\nOriginal Array =',a)

#setting new number in array with 'append()'
a = np.append(a,-3)
a

#defining a list of  numbers in the original array with 'append()'
a = np.append(a,[1,2,3])
a

#creating a 2D array
b = np.array([[2,4,6,7],[4,6,8,9]])
b

#adding a row of values ​​in the last position 
np.append(b,[[7,1,9,2]],axis=0)

#adding a row of values ​​in the first position 
b=np.append([[7,1,9,2]],b,axis=0)

#adding a column using 'append'
np.append(b,[[6],[9],[30]],axis=1)

c = np.array([[4,5,7,1],[7,5,2,3]])
c

#inserting a row in the first position using 'insert()'
np.insert(c,0,[1,10,5,8],axis=0)

#the original matrix does not change
print('\nOriginal c =',c)

#inserting a row in the second position using 'insert()'
np.insert(c,1,[1,10,5,8],axis=0)

#inserting a row in the third position using 'insert()'
np.insert(c,2,[1,10,5,8],axis=0)

#inserting a line of zeros
np.insert(c,2,0,axis=0)

#inserting a column in the first position using 'insert()'
np.insert(c,0,[1, 10],axis=1)

#inserting a column in the second position using 'insert()'
np.insert(c,1,[1, 10],axis=1)

#inserting a column in the third position using 'insert()'
np.insert(c,2,[1, 10],axis=1)