# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17BIQd6m_5AR2ZBewM45Q5UF0UDRFN6Lb
"""

import numpy as np

"""linearly spaced vector"""

X = np.linspace(0,1,11)
print(X)

X = np.linspace(0,1,11,retstep=True)
print(X)

X = np.linspace(0,1,11,endpoint=False)
print(X)

"""Absolute value"""

X = np.array([-3,-2,-1,0,1,2,3])
Y = np.abs(X)
print(Y)

"""Highest value position"""

X = [1,4,7,1,0,2]
np.argmax(X)

X[np.argmax(X)]

"""
Position of the lowest value"""

np.argmin(X)

X[np.argmin(X)]

"""
powers"""

X = np.array([1,2,3,4,5])
Y = np.power(X,2)
print(Y)

power_Z = np.array([1,3,2,4,5])
Z = np.power(X,power_Z)
print(Z)

"""
Leases"""

X = [1.12,1.46,1.51,1.69,1.82,1.999]

"""closest value"""

Y = np.around(X)
print(Y)

"""Considering one decimal place"""

Z = np.around(X, decimals=1)
print(Z)

"""
nearest integer value"""

W = np.rint(X)
print(W)