# -*- coding: utf-8 -*-
"""Untitled70.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzqEbgiXy2Kj0Q9Mdcmg8AeBIkTNPcia
"""

import pandas as pd
import numpy as np
my_array = np.random.randint(1,20,size=(3,4))
print(my_array)
my_array.tofile('D:\CarPrice.csv',sep=',')

df = pd.read_csv('/content/D:\CarPrice.csv')
print(df)

import pandas as pd
import numpy as np
my_array = np.random.randint(1,20,size=(3,4))
print(my_array)
np.savetxt('D:\CarPrice.csv',my_array,delimiter=',')

df = pd.read_csv('/content/D:\CarPrice.csv')
print(df)

import numpy as np
loaded_array = np.genfromtxt('D:\CarPrice.csv',delimiter=',')
print(loaded_array)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0,20,20)
print(x_vals)
y_vals = [math.sqrt(i) for i in x_vals]
plt.plot(x_vals,y_vals)

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0,20,20)
y_vals = [math.sqrt(i) for i in x_vals]
y2_vals = x_vals ** 3
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('squared Roots')
plt.plot(x_vals, y_vals, 'r',label = 'squared Root')
plt.plot(x_vals,y2_vals,'b',label='Cube')
plt.legend(loc='upper center')

import numpy as np
import matplotlib.pyplot as plt
my_array = np.random.randint(1,20,size=(4,4))
print(my_array)
plt.imshow(my_array)
plt.show()

import numpy as np
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print(np_sqr)

import numpy as np
nums = [10,20,30,40,50]
np_log = np.log(nums)
print(np_log)

nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print(np_exp)

nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print(np_sine)
nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print(np_cos)