# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-sYLKmC3eaoD8-e-8T_38-QO26TrKDG
"""

import pandas as pd
import numpy as np
from datetime import datetime
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
d = datetime(2019, 6, 3, 0, 0, 0)
print(df.at[d,'B'])

import pandas as pd
import numpy as np
from datetime import datetime
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df[(df.A>0)&(df.B>0)])

import pandas as pd
import numpy as np
from datetime import datetime
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.transpose())
print(df.T)

import pandas as pd
import numpy as np
from datetime import datetime
var = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(var)
def checkSeriesOrDataframe(var):
  if isinstance(var,pd.DataFrame):
    print("The output is: Dataframe")
  if isinstance(var,pd.Series):
    print("The output is: Series")

checkSeriesOrDataframe(df)

