# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6op5LCdTqWkvsLRNgoE0DZMy_EJdJfM
"""

import pandas as pd
series = pd.Series([1,2,3,4,5])
print(series)

import pandas as pd
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series)

import pandas as pd
series = pd.Series([1,2,3,4,5])
print(series[2])
print(series.iloc[2])

import pandas as pd
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series['d'])
print(series.loc['d'])

import pandas as pd
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series['d'])
print(series.loc['d'])

import pandas as pd
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series['c'])
print(series.loc['c'])

import pandas as pd
series = pd.Series([1,2,3,4,5])
print(series[2:])
print(series.iloc[2:])

