# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117ULqEqpOyHRL_lRaUNYR0WfngiITTCc
"""

import pandas
mydataset = {'cars': ["BMW", "Volvo", "Ford"], 'Model Number': [3,1,2]}
myvar = pandas.DataFrame(mydataset)
print(myvar)

import pandas as pd
mydataset = {'cars': ["BMW", "Volvo", "Ford"], 'Model Number': [3,1,2]}
myvar = pd.DataFrame(mydataset)
print(myvar)

import pandas as pd
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

import pandas as pd
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories, index = ["day1", "day2"])
print(myvar)

