# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJJYnnp97qNvKUK1t1EwkRh9G75ERRsz
"""

import numpy 
import pandas 
df=pandas.DataFrame(numpy.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.head())

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.head(8))

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.head(2))

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.tail())

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.tail(8))

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df['A'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df[['A','B']])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df[2:4])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.iloc[2:4])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.iloc[[2,4]])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.iloc[2])

