# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dENgUbh0s4Jh0VwiTYKa0h9yqfozUdbh
"""

import pandas as pd
df=pd.read_csv('/content/data.csv')
df['Date'] = pd.to_datetime(df['Date'])
print(df.to_string())

import pandas as pd
df=pd.read_csv('/content/data.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.dropna(subset=['Date'],inplace=True)
print(df.to_string())

import pandas as pd
df=pd.read_csv('/data_1.0.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.dropna(subset=['Date'],inplace=True)
df.loc[3,'Age'] = 4
print(df.to_string())

import pandas as pd
df=pd.read_csv('/data_1.0.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.dropna(subset=['Date'],inplace=True)
for x in df.index:
    if df.loc[x,"Age"] > 100:
        df.loc[x,"Age"] = 4
print(df.to_string())

import pandas as pd
df=pd.read_csv('/data_1.0.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.dropna(subset=['Date'],inplace=True)
for x in df.index:
    if df.loc[x,"Age"] > 100:
        df.drop(x,inplace=True)
print(df.to_string())