# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HDGG8mBX2r__w9SGZJP358u8rJu0j1GQ
"""

import pandas as pd
dates1=pd.date_range('20210629', periods=12)
print(dates1)

import pandas as pd
dates1=pd.date_range('20210629', periods=12)
series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
series.index = dates1
print(series)

import pandas as pd
dates2=pd.date_range('2021-06-29', periods=12, freq='M')
print(dates2)

import pandas as pd
dates2=pd.date_range('2021-06-29', periods=12, freq='MS')
print(dates2)

import pandas as pd
dates2=pd.date_range('29-06-2021', periods=12, freq='MS')
print(dates2)

import pandas as pd
dates3 = pd.date_range('2021/06/29 09:00:00', periods=8, freq='H')
print(dates3)

