# -*- coding: utf-8 -*-
"""Untitled91.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ISP3pkbaXfpQ9HnO51rI2ZL4WOGAZXGD
"""

import matplotlib.pyplot as plt
import seaborn as sns 
import pandas as pd
sns.set_style("darkgrid")
titanic_data = sns.load_dataset('titanic')

pd.crosstab(titanic_data["class"],titanic_data["age"],margins=True)

titanic_data['age_group']=pd.cut(x = titanic_data['age'],
 bins = [0,5,20,60,100],
 labels = ["toddler", "young", "adult","senior"])
titanic_data['age_group'].value_counts()

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(6)
print(x)
print(type(x))

y=x+1
print(y)
plt.plot(x, y, 'o--')
plt.show()

x = np.arange(2, 6)
print(x)
y = x + 1

a= np.arange(2, 6, 2)
print(a)
b = a + 1

plt.plot(x, y, 'o--')
plt.plot(a, -b, 'o-')
plt.show()

plt.plot(x, y, 'o--')
plt.plot(x, -y, 'o-')
plt.title('y=x and y=-x')
plt.show()

N = 16
x = np.linspace(0, 15, N)
print(x)
y = x
plt.plot(x, y, 'o--')
plt.axis('off')
plt.show()