# -*- coding: utf-8 -*-
"""Untitled81.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xetDidIdeHCZjHCMZpU0o8JtmTDv8-KH
"""

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")
titanic_data = sns.load_dataset('titanic')
titanic_data.head()

print(titanic_data["class"])
type(titanic_data["class"])

print(type(titanic_data[["class", "sex", "age"]]))
titanic_data[["class", "sex", "age"]]

my_df = titanic_data[titanic_data["embarked"] == "S"]
my_df.head()

my_df = titanic_data[(titanic_data["sex"] == "male") &
(titanic_data["class"] =="First")]
my_df.head()

ages = [20,21,22]
age_dataset = titanic_data[titanic_data["age"].isin(ages)]
age_dataset.head()

import pandas as pd
scores = [
{'Subject':'Mathematics', 'Score':85, 'Grade': 'B', 'Remarks': 'Good',
},
{'Subject':'History', 'Score':98, 'Grade': 'A','Remarks':
'Excellent'},
{'Subject':'English', 'Score':76, 'Grade': 'C','Remarks': 'Fair'},
{'Subject':'Science', 'Score':72, 'Grade': 'C','Remarks': 'Fair'},
{'Subject':'Arts', 'Score':95, 'Grade': 'A','Remarks': 'Excellent'},
]
my_df = pd.DataFrame(scores)
my_df.head()

print(my_df.loc[2])
type(my_df.loc[2])

my_df.loc[2:4]

my_df.loc[2:4, ["Grade", "Score"]]

