# -*- coding: utf-8 -*-
"""Untitled72.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XnbgNKwtbg4CID08PPhsLMrtSx6AIb9o
"""

import pandas as pd
my_series = pd.Series()
print(my_series)

import pandas as pd
import numpy as np
my_array = np.array([10, 20, 30, 40, 50])
my_series = pd.Series(my_array)
print(my_series)

import pandas as pd
import numpy as np
my_array = np.array([10, 20, 30, 40, 50])
my_series = pd.Series(my_array, index = ["num1", "num2", "num3", "num4", "num5"])
print(my_series)

import pandas as pd
import numpy as np
my_series = pd.Series([10, 20, 30, 40, 50],index = ["num1", "num2", "num3", "num4", "num5"])
print(my_series)

import numpy as np
import pandas as pd
my_series = pd.Series(25, index = ["num1","num2","num3","num4","num5"])
print(my_series)

import pandas as pd
import numpy as np
my_dict = {'num1' :6,
'num2' :7,
'num3' :8}
my_series = pd.Series(my_dict)
print(my_series)

import pandas as pd
my_series = pd.Series([10, 20, 30, 40, 50],index = ["num1", "num2", "num3", "num4", "num5"])
print(my_series[0])
print(my_series['num3'])

import pandas as pd
import numpy as np
my_series = pd.Series([5,8,2,11,9])
print(np.min(my_series))
print(np.max(my_series))

import pandas as pd
import numpy as np
my_series = pd.Series([5,8,2,11,9])
print(my_series.mean())

import numpy as np
import pandas as pd
my_series = pd.Series([5, 8, 2, 11, 9])
print(my_series.dtype)

