# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVKfojvQcf7B3swJczrRK0k4SLHo9b3C
"""

import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)

import pandas as pd
df=pd.read_csv('/data.csv')
print(df)

import pandas as pd
df=pd.read_csv('/data.csv')
days = pd.date_range('20190525', periods=3)
df.index = days
print(df)

import pandas as pd
df=pd.read_csv('/data.csv')
days = pd.date_range('20190525', periods=3)
df.index = days
print(df)
print(df.index)

import pandas as pd
df=pd.read_csv('/data.csv')
days = pd.date_range('20190525', periods=3)
df.index = days
print(df)
print(df.index)
print(df.values)