# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qO8uCXPnCj3RFZ6mThOxuPMNbsegAxyl
"""

import pandas as pd
df=pd.read_csv('/content/data_1.0.csv')
print(df.to_string())
print(df.duplicated())

import pandas as pd
df=pd.read_csv('/content/data_1.0.csv')
print(df.to_string())
df.corr()

