# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OY7sonTOe9WvPRFQUBuTQ0HUWANNM0Ft
"""

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.iloc[2:4,1:4])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.iloc[[2,4], [1,3]])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
print(df['20190601':'20190603'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
print(df.loc['20190601':'20190603'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
print(df.loc['20190601':'20190603','A':'C'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
days = pd.date_range('20190601', periods=10)
df.index=days
print(df.loc['20190601':'20190603','A':'C'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
days = pd.date_range('20190601', periods=10)
df.index=days
print(df.loc['20190601':'20190603',['A','C']])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
days = pd.date_range('20190601', periods=10)
df.index=days
print(df.loc['20190601'])

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
print(df.loc[['20190601','20190603']])

import numpy as np
import pandas as pd
from datetime import datetime
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
date1=datetime(2019,6,1,0,0,0)
date2=datetime(2019,6,3,0,0,0)
print(df.loc[[date1,date2]])

import numpy as np
import pandas as pd
from datetime import datetime
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
date1=datetime(2019,6,1,0,0,0)
date2=datetime(2019,6,3,0,0,0)
print(df.loc[date1,['A','C']])

