# -*- coding: utf-8 -*-
"""Untitled84.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktfojs0F2wf_MlbJvXQPyi62TvTAZX1Y
"""

import pandas as pd
scores = [
{'Subject':'Mathematics', 'Score':85, 'Grade': 'B', 'Remarks': 'Good',},
{'Subject':'History', 'Score':98, 'Grade': 'A','Remarks':'Excellent'},
{'Subject':'English', 'Score':76, 'Grade': 'C','Remarks': 'Fair'},
{'Subject':'Science', 'Score':72, 'Grade': 'C','Remarks': 'Fair'},
{'Subject':'Arts', 'Score':95, 'Grade': 'A','Remarks': 'Excellent'},]
my_df = pd.DataFrame(scores, index = ["Student1", "Student2", "Student3",
"Student4", "Student5"])
my_df

my_df.loc["Student1"]

index_list = ["Student1", "Student2"]
my_df.loc[index_list]

my_df.loc["Student1", "Grade"]

my_df.loc["Student1":"Student2", "Grade"]

my_df.loc["Student1":"Student4", "Grade"]

my_df.loc[[False, False, False, True, False]]

my_df["Score"]>80

my_df.loc[my_df["Score"]>80]

my_df.loc[(my_df["Score"]>80) & (my_df["Remarks"] == "Excellent")]

my_df.loc[my_df["Score"]>80, ["Score","Grade"]]

my_df.loc["Student4"] = 90
my_df