# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MpbCwb9u1f_LSrXm3XkVcK07TBRQrmCk
"""

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
titanic_data = sns.load_dataset('titanic')
titanic_data.head()

titanic_data["class"].unique()

titanic_data["class"].nunique()

titanic_data.count()

titanic_data["class"].value_counts()

titanic_gbclass = titanic_data.groupby("class")
print(titanic_gbclass)

titanic_gbclass.ngroups

titanic_gbclass.size()

titanic_gbclass.size

titanic_gbclass.groups["First"]

titanic_gbclass.last()

titanic_second_class = titanic_gbclass.get_group("Second")
titanic_second_class.head()

titanic_gbclass.age.max()

titanic_gbclass.fare.agg(['max', 'min', 'count', 'median', 'mean'])