# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2N0J8JpYWMNBNjpHjpnNOIX42p2xpgi
"""

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.sort_index(axis=0,ascending=False)) #axis = 0 means sort by #index

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.sort_index(axis=1,ascending=False)) #axis = 1 means sort by #column

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.sort_values('A',axis=0))

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
days = pd.date_range('20190601', periods=10)
df.index=days
print(df)
print(df.sort_values('20190601',axis=1))

