# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BD3YLSAQBdWGYf69b5s7UWa_BAw0DQcK
"""

import pandas as pd
import numpy as np
my_series = pd.Series([5,8,2,11,9])
print(my_series.tolist())

import pandas as pd
my_df = pd.DataFrame()
print(my_df)

import pandas as pd
scores = [['Mathematics',85],['English',91],['History',95]]
my_df = pd.DataFrame(scores, columns = ['Subject','Score'])
my_df

import pandas as pd
scores = {'Subject':["Mathematics","History","English","Science","Arts"],'Score':[98,75,68,82,99]}
my_df = pd.DataFrame(scores)
my_df

import pandas as pd
scores = [{'Subject':'Mathematics','Score':85},{'Subject':'History','Score':98},
          {'Subject':'English','Score':76},{'Subject':'Science','Score':72},
          {'Subject':'Arts','Score':95},]
my_df = pd.DataFrame(scores)
my_df

import pandas as pd
scores = [{'Subject':'Mathematics', 'Score':85}, {'Subject':'History', 'Score':98},
{'Subject':'English', 'Score':76}, {'Score':72}, {'Subject':'Arts', 'Score':95}]
my_df = pd.DataFrame(scores)
my_df

import pandas as pd
scores = [{'Subject':'Mathematics', 'Score':85},
{'Subject':'History', 'Score':98},
{'Subject':'English', 'Score':76},
{'Subject':'Science', 'Score':72},
{'Subject':'Arts', 'Score':95},
]
my_df=pd.DataFrame(scores)
my_df.head(3)

import pandas as pd
scores = [{'Subject':'Mathematics', 'Score':85},
{'Subject':'History', 'Score':98},
{'Subject':'English', 'Score':76},
{'Subject':'Science', 'Score':72},
{'Subject':'Arts', 'Score':95},
]
my_df=pd.DataFrame(scores)
my_df.tail(2)

import pandas as pd
scores = [{'Subject':'Mathematics', 'Score':85},
{'Subject':'History', 'Score':98},
{'Subject':'English', 'Score':76},
{'Subject':'Science', 'Score':72},
{'Subject':'Arts', 'Score':95},
]
my_df=pd.DataFrame(scores)
my_df.info()

import pandas as pd
scores = [{'Subject':'Mathematics', 'Score':85},
{'Subject':'History', 'Score':98},
{'Subject':'English', 'Score':76},
{'Subject':'Science', 'Score':72},
{'Subject':'Arts', 'Score':95},
]
my_df=pd.DataFrame(scores)
my_df.describe()