# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ofFymQCRQQ3yJLuHlnY27OzE6LCQYnz6
"""

import pandas as pd
df = pd.DataFrame({"Gender": ['Male','Male','Female','Female','Female'], "Team" : [1,2,3,3,1] })
print(df)

import pandas as pd
df = pd.DataFrame({"Gender": ['Male','Male','Female','Female','Female'], "Team" : [1,2,3,3,1] })
print(df)
print("Displaying the distribution of genders in each team")
print(pd.crosstab(df.Gender, df.Team))

import pandas as pd
df = pd.DataFrame({"Gender": ['Male','Male','Female','Female','Female'], "Team" : [1,2,3,3,1] })
print(df)
print("Displaying the distribution of teams in each gender")
print(pd.crosstab(df.Team, df.Gender))

import pandas as pd
import numpy as np

# creating some data
a = np.array(["foo","foo","foo","foo","bar","bar","bar","bar","foo","foo","foo"], dtype=object)
b = np.array(["one","one","one","two","one","one","one","two","two","two","one"], dtype=object)
c = np.array(["dull","dull","shiny","dull","dull","shiny","shiny","dull","shiny","shiny","shiny"], dtype=object)

# form the cross tab
pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])

