# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vt2KXosrNlhoi1j-5ikLRq0s-OJyd4ty
"""

import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.describe())

import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.mean(0))

import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)
print(df.mean(1))

