# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d1MmtJ-vG9JyFJddaXgHbU8r8Zy3cly_
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
data = pd.read_csv('/content/drivinglicence.csv')
#plot a factorplot
g = sns.catplot(x="gender",y="licence",col="class",data=data,kind="bar",ci=None,
aspect=1.0)
#set the labels
g.set_axis_labels("","Proportion with Driving licence")
g.set_xticklabels(["Men","Women"])
g.set_titles("{col_var} {col_name}")
#show plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
titanic=sns.load_dataset("titanic")
g = sns.catplot(x="who",y="survived",col="class",data=titanic,kind="bar",
ci=None,aspect=1)
g.set_axis_labels("","Survival Rate")
g.set_xticklabels(["Men","Women","Children"])
g.set_titles("{col_name} {col_var}")
plt.show()

