# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxrIE9uQ9-BY7BOtvUUCJdOcsOOI3CEK
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
labels = ["Chrome","Internet Explorer","Firefox","Edge","Safari","Sogou Explorer","Opera","Others"]
marketshare = [61.64,11.98,11.02,4.23,3.79,1.63,1.52,4.19]
explode = (0,0,0,0,0,0,0,0)
plt.pie(marketshare,
explode = explode,
labels = labels,
autopct="%.1f%%",
shadow=True,
startangle=0)
plt.axis("equal")
plt.title("Web Browser Marketshare - 2021")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
labels = ["Chrome","Internet Explorer","Firefox","Edge","Safari","Sogou Explorer","Opera","Others"]
marketshare = [61.64,11.98,11.02,4.23,3.79,1.63,1.52,4.19]
explode = (0,0,0,0,0,0,0,0)
plt.pie(marketshare,
explode = explode,
labels = labels,
autopct="%.1f%%",
shadow=True,
startangle=60)
plt.axis("equal")
plt.title("Web Browser Marketshare - 2021")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
labels = ["Chrome","Internet Explorer","Firefox","Edge","Safari","Sogou Explorer","Opera","Others"]
marketshare = [61.64,11.98,11.02,4.23,3.79,1.63,1.52,4.19]
explode = (0,0,0,0,0,0,0,0)
pie=plt.pie(marketshare,
explode = explode,
labels = labels,
autopct="%.1f%%",
shadow=True,
startangle=45)
plt.axis("equal")
plt.title("Web Browser Marketshare - 2021")
plt.legend(pie[0],labels,loc="best")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
labels = ["Chrome","Internet Explorer","Firefox","Edge","Safari","Sogou Explorer","Opera","Others"]
marketshare = [61.64,11.98,11.02,4.23,3.79,1.63,1.52,4.19]
explode = (0,0,0,0,0,0,0,0)
pie=plt.pie(marketshare,
explode = explode,
labels = labels,
autopct="%.1f%%",
shadow=True,
startangle=45)
plt.axis("equal")
plt.title("Web Browser Marketshare - 2021")
plt.legend(pie[0],labels,loc=3)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
labels = ["Chrome","Internet Explorer","Firefox","Edge","Safari","Sogou Explorer","Opera","Others"]
marketshare = [61.64,11.98,11.02,4.23,3.79,1.63,1.52,4.19]
explode = (0,0,0,0,0,0,0,0)
plt.pie(marketshare,
explode = explode,
labels = labels,
autopct="%.1f%%",
shadow=True,
startangle=45)
plt.axis("equal")
plt.title("Web Browser Marketshare - 2021")
plt.savefig("web browser.png", bbox_inches="tight")
plt.show()