# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/194sCvaM4A_mrHf-9-hnjeE2eZZ8ELzAQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],
         [1,8,27,64],
         'bo')
plt.axis([0, 4.5, 0, 70])
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
a = np.arange(1,4.5,0.1)
plt.plot(a, a**2, 'y^',
         a, a**3, 'bo',
        a, a**4, 'r--',)
plt.axis([0, 4.5, 0, 70])
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
a = np.arange(1,5,0.1)
plt.subplot(121)
plt.plot([1,2,3,4,5],[1,8,27,64,125],'y^')
plt.subplot(122)
plt.plot(a,a**2,'y^',a,a**3,'bo',a,a**4,'r--',)
plt.axis([0,4.5,0,70])
plt.show()

