# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d38pdrd3qEXC4VbTBy5JIWKjbSPZlw_X
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error

train_data = pd.read_csv('/content/train (1).csv')

train_data

X = np.array(train_data['x']).reshape(-1,1)
y = np.array(train_data['y']).reshape(-1,1)

X_test, X_train, y_test,y_train = train_test_split(X,y,test_size=0.3,random_state=1)

model = LinearRegression().fit(X_train, y_train)

model.coef_

model.intercept_

y_pred = model.predict(X_test)
y_pred

mse = mean_squared_error(y_test,y_pred)
mse

rsq = r2_score(y_test,y_pred)
rsq

plt.scatter(X,y)
plt.plot(X_test,y_pred,color='red')