# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhcJWS9BWlh8V3HtcZNQRnkX3sCxzf8R
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

datadf = pd.read_csv("/content/framingham.csv")
datadf.head()

datadf.shape

datadf.describe()

datadf.isnull().sum()

datadf['education'] = datadf['education'].fillna(1.0)
datadf['cigsPerDay'] = datadf['cigsPerDay'].fillna(0.0)
datadf['BPMeds'] = datadf['BPMeds'].fillna(0.0)

t_mean = datadf['totChol'].mean()
datadf['totChol'] = datadf['totChol'].fillna(t_mean)
t_mean

b_mean = datadf['BMI'].mean()
datadf['BMI'] = datadf['BMI'].fillna(b_mean)
b_mean

g_mean = datadf['glucose'].mean()
datadf['glucose'] = datadf['glucose'].fillna(g_mean)
g_mean

h_mean = datadf['heartRate'].mean()
datadf['heartRate'] = datadf['heartRate'].fillna(h_mean)
h_mean

datadf.rename(columns={'male':'gender'},inplace=True)
datadf.head()

X = datadf.drop('TenYearCHD',axis=1)
y = datadf['TenYearCHD']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

logreg = LogisticRegression(max_iter=20000).fit(X_train,y_train)

logreg.score(X_train,y_train)

prediction = logreg.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :- \n",accuracy_score(y_test,prediction,normalize=True))

print("\nClassification report :- \n",classification_report(y_test,prediction))

print("\nConfusion Matrix :- \n",confusion_matrix(y_test,prediction))

