# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBxyVxBunq3pm7EskDW4WPPTxUOuefEW
"""

from sklearn.datasets import load_iris

iris = load_iris()
type(iris)

from sklearn.datasets import load_iris

iris = load_iris()
X=iris.data
Y=iris.target

X

Y

len(X)

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.3,random_state=1)

print(X_train.shape)

print(X_test.shape)

print(Y_test.shape)

print(Y_train.shape)

