# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EmxTmMmXBS6x5zNo6IOvFtXahbsmApuh
"""

from sklearn import svm,datasets,metrics

X,y = datasets.load_iris(return_X_y=True)

X_train = X[range(1,150,1),:]
y_train = y[range(1,150,1)]

X_test = X[range(0,150,2),:]
y_test = y[range(0,150,2)]

clf = svm.LinearSVC().fit(X_train,y_train)

prediction = clf.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test,prediction,normalize=True))

print("\nClassification report :- \n",metrics.classification_report(y_test,prediction))

print("\nConfusion matrix :- \n",metrics.confusion_matrix(y_test,prediction))

