# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTQlJg_1oK9bdrZ4AxHG_xZz8LWDtFZp
"""

import numpy as np
from sklearn.linear_model import SGDClassifier, SGDRegressor

X = np.array([[-1,-1],[-2,-1],[1,1],[2,1]])
y = np.array([1,1,2,2])

clf = SGDClassifier(max_iter=1000,tol=1e-3,penalty="elasticnet")
clf.fit(X,y)

clf.predict([[2,2]])

clf.coef_

clf.intercept_

clf1 = SGDRegressor(max_iter=1000,penalty="elasticnet",loss="huber",tol=1e-3,average=True)
clf1.fit(X,y)

clf1.coef_