# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVAFUDRevb0Sw29o99GfF6x4gD6LTv_c
"""

from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn import datasets,metrics
from sklearn.tree import export_graphviz
import pydotplus

X,y = datasets.load_iris(return_X_y=True)

X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

tree = DecisionTreeClassifier(criterion= 'entropy').fit(X_train,y_train)

export_graphviz(tree, out_file='abc.dot')

prediction = tree.predict(X_test)
prediction

metrics.accuracy_score(y_test,prediction,normalize=True)

print(metrics.classification_report(y_test,prediction))

metrics.confusion_matrix(y_test,prediction)

clf_gini = DecisionTreeClassifier(criterion="gini").fit(X_train,y_train)

prediction = tree.predict(X_test)
prediction

metrics.accuracy_score(y_test,prediction,normalize=True)

print(metrics.classification_report(y_test,prediction))

metrics.confusion_matrix(y_test,prediction)

clf_gini.predict([[0,10,3,0]])