# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cc-XvQvIcHCi8W2h8OYC5XzFpK5IIWqm
"""

from sklearn import neighbors,datasets,metrics
from sklearn .model_selection import GridSearchCV

X,y = datasets.load_iris(return_X_y=True)

X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2)]
y_test = y[range(1,150,2)]

classifier = neighbors.KNeighborsClassifier()

param_grid = {'n_neighbors' : [3,5,10,15,6,7,13], 'weights' : ['uniform','distance'], 'metric' : ['manhattan','euclidean']}

clf = GridSearchCV(classifier,param_grid,cv = 7)
clf.fit(X_train,y_train)

clf.best_params_

prediction = clf.predict(X_test)
prediction

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test,prediction,normalize=True))

print("\nClassification report :- \n",metrics.classification_report(y_test,prediction))

print("\nConfusion Matrix :- \n",metrics.confusion_matrix(y_test,prediction))

