# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FwnELfvZqOWMWO_PBsRF3HlT5cYcQQC0
"""

from scipy import misc, ndimage
import numpy as np
from matplotlib import pyplot as plt

face = misc.face(gray=True)
plt.imshow(face,cmap=plt.cm.gray)

x = ndimage.shift(face, (100,100))
plt.imshow(x, cmap=plt.cm.gray)

y = ndimage.shift(face, (50,50),mode='nearest')
plt.imshow(y,cmap=plt.cm.gray)

y = ndimage.shift(face, (50,50),mode='constant')
plt.imshow(y,cmap=plt.cm.gray)

y = ndimage.shift(face, (50,50),mode='reflect')
plt.imshow(y,cmap=plt.cm.gray)

z = ndimage.rotate(face,30)
plt.imshow(z,cmap=plt.cm.gray)

z = ndimage.rotate(face,30,mode='wrap')
plt.imshow(z,cmap=plt.cm.gray)

a = face[50:-50,50:-50]
plt.imshow(a, cmap=plt.cm.gray)

a = face[50:-50,50:-5]
plt.imshow(a, cmap=plt.cm.gray)

b = ndimage.zoom(face,2)
plt.imshow(b, cmap=plt.cm.gray)

b = ndimage.zoom(face,5)
plt.imshow(b, cmap=plt.cm.gray)

img = face[:512,-512:]
noisy = np.copy(img).astype(np.float)
noisy = noisy + img.std()*0.5*np.random.standard_normal(img.shape)

plt.imshow(noisy, cmap=plt.cm.gray)

plt.imshow(img,cmap=plt.cm.gray)

blurry = ndimage.gaussian_filter(noisy, sigma=3)  
plt.imshow(blurry,cmap=plt.cm.gray)

blurry = ndimage.gaussian_filter(noisy, sigma=5)  
plt.imshow(blurry,cmap=plt.cm.gray)

median_face = ndimage.median_filter(blurry, size=5)
plt.imshow(median_face,cmap=plt.cm.gray)

a = np.zeros((7,7),dtype=np.int)
a[1:6,2:5] = 1
a

ndimage.binary_erosion(a).astype(a.dtype)

ndimage.binary_dilation(a).astype(a.dtype)

"""closing -> dilation, erosion
opening -> erosion, dilation
"""

