# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13A1X4gahCRiM9p-_Yd44pngYnFUkASjD
"""

from scipy import stats
import numpy as np
from matplotlib import pyplot as plt

#creating an array of specified shape and the filling with random values.
samples = np.random.normal(size=1000)
samples

bins = np.arange(-4,5)
bins

histogram = np.histogram(samples, bins=bins , density=True)[0]
histogram

bins = 0.5*(bins[1:] + bins[:-1])
bins

pdf = stats.norm.pdf(bins)

plt.plot(bins,histogram)

plt.plot(bins,pdf)

loc, std = stats.norm.fit(samples)

loc

std

stats.scoreatpercentile(samples,50)

np.median(samples)

stats.scoreatpercentile(samples,90)

a=np.random.normal(0,1,size=100)
b=np.random.normal(1,1,size=10)

stats.ttest_ind(a,b)

#scipy.integrate
#scipy.optimize
#scipy.fftpack
#scipy.ndimage